config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "maps#index"

  resources :maps, only: [:index]
  resources :users, only: [:show, :edit, :update]
  resources :aboutmes

  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end

end

app/models/aboutme.rb
class Aboutme < ApplicationRecord

  validates :content, :image, :url, presence: true

  belongs_to :user

  mount_uploader :image, ImageUploader

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord

  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages

  validates :name, presence: true, uniqueness: true

  def show_last_message
    if (last_message = messages.last).present?
      if last_message.content?
        last_message.content
      else
        "--> photo"
      end
    else
      " Let's Knock!"
    end
  end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord

  belongs_to :group
  belongs_to :user

end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :group
  belongs_to :user

  validates :content, presence: true, unless: :image?

  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true

  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
  has_many :aboutmes

end

app/controllers/aboutmes_controller.rb
class AboutmesController < ApplicationController

  def index
    @abouts = Aboutme.includes(:user).all
  end

  def new
    @about = Aboutme.new
  end

  def create
    @about = Aboutme.new(about_params)
      if @about.save
          redirect_to aboutmes_path, notice: "新規About作成成功！"
      else
        redirect_to new_aboutme_path, notice: "再作成してください"
      end
  end

  def show
    @about = Aboutme.find(params[:id])
  end

  def edit
    @about = Aboutme.find(params[:id])
  end

  def update
    about = Aboutme.find(params[:id])
    about.update(about_params)
    redirect_to aboutme_path(about.id)
  end

  def destroy
    about = Aboutme.find(params[:id])
    about.destroy
    redirect_to aboutmes_path
  end


  private
  def about_params
    params.require(:aboutme).permit(:content, :image, :url).merge(user_id: current_user.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: "Doorを新規作成"
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to group_messages_path(current_user), notice: "ノック相手更新しました"
    else
      render :edit
    end
  end


  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

  def index
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :set_group, only: [:index, :create]

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      redirect_to group_messages_path(@group), notice: 'メッセージ送信完了'
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージ入力プリ-ズ'
      render :index
    end
  end


  private
  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @abouts = @user.aboutmes
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/aboutmes/edit.html.haml
.header
  .header__title
    = link_to "About Me", aboutmes_path, class: "header__title--text"
  .header__right
    = link_to current_user.name, user_path(current_user), class: "header__right--btn"
    = link_to "ノックノック画面に戻る", root_path, class: "header__right--btn"
    = link_to "新規プロフィール作成はこちら", new_aboutme_path, class: "header__right--btn"
.contents
  -# = yield
  .profileTitle
    プロフィールの編集

  .profileDatas
    .profileData
      = form_for @about do |fo|
        .newText
          = fo.label :name, "プロフィールを書こう"
          %br
          = fo.text_area :content, class: "newTextZ", placeholder: "国籍/ルート/期間/一言！"
        .newImage
          = fo.label :name, "写真アイコンを貼ろう"
          %br
          %i.fab.fa-tripadvisor
            = fo.file_field :image, class: "newImageZ"
        .newUrl
          = fo.label :name, "SNSのURLを貼ろう"
          %br
          = fo.url_field :url, class: "newUrlZ"
        .newSendBtn
          = fo.submit "新About決定ボタン", class: "newSendBtnZ"

app/views/aboutmes/index.html.haml
.header
  .header__title
    = link_to "About Me", aboutmes_path, class: "header__title--text"
  .header__right
    = link_to  current_user.name, user_path(current_user), class: "header__right--btn"
    = link_to "ノックノック画面に戻る", root_path, class: "header__right--btn"
    = link_to "新規プロフィール作成はこちら", new_aboutme_path, class: "header__right--btn"
.contents
  -# = yield
  - @abouts.each do |about|
    .cpontent

      .content__left
        .content__left--image
          = image_tag about.image

      .content__right
        .content__right__top
          = link_to about.content, aboutme_path(about.id), class: "content__right__top--title"

        .content__right__middle
          = about.url
        .content__right__bottom
          .content__right__bottom--date
            = about.user.name
            -# user_idとアソシエーションより別テーブルからもってくる
            = about.created_at

app/views/aboutmes/new.html.haml
.header
  .header__title
    = link_to "About Me", aboutmes_path, class: "header__title--text"
  .header__right
    = link_to current_user.name, user_path(current_user), class: "header__right--btn"
    = link_to "ノックノック画面に戻る", root_path, class: "header__right--btn"
    = link_to "新規プロフィール作成はこちら", new_aboutme_path, class: "header__right--btn"
.contents
  -# = yield
  .profileTitle
    新規プロフィールボタンリンク→About me(新規投稿プロフィール)
    タイムゾーン
    スポット
    編集ボタンと削除ボタン

  .profileDatas
    .profileData
      = form_for @about do |fo|
        .newText
          = fo.label :name, "プロフィールを書こう"
          %br
          = fo.text_area :content, class: "newTextZ", placeholder: "国籍/ルート/期間/一言！"

        .newImage
          = fo.label :name, "写真アイコンを貼ろう"
          %br
          %i.fab.fa-tripadvisor
            = fo.file_field :image, class: "newImageZ"
        .newUrl
          = fo.label :name, "SNSのURLを貼ろう"
          %br
          = fo.url_field :url, class: "newUrlZ"

        .newSendBtn
          = fo.submit "新About決定ボタン", class: "newSendBtnZ"

app/views/aboutmes/show.html.haml
.header
  .header__title
    = link_to "About Me", aboutmes_path, class: "header__title--text"
  .header__right
    = link_to current_user.name, user_path(current_user), class: "header__right--btn"
    = link_to "ノックノック画面に戻る", root_path, class: "header__right--btn"
    = link_to "新規プロフィール作成はこちら", new_aboutme_path, class: "header__right--btn"
.contents
  -# = yield

  .aboutImage
    - if @about.image?
      = image_tag @about.image.url
    - else
      = image_tag "noimage.gif"

  .aboutUrl
    = @about.url
  .aboutDate
    = @about.created_at
  .aboutAuthor

  - if user_signed_in? && current_user.id == @about.user_id
    .aboutManage
      = link_to "プロフ編集はここから", edit_aboutme_path(@about.id), class: "postManage__edit"
      = link_to "プロフ削除はここから", aboutme_path(@about.id), method: :delete, class: "postManage__delete"

  .aboutText
    = simple_format @about.content

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました〜"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message

  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    -# この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      -# グループ作成機能の追加時はここにcollection_check_boxesの記述を追記
      = f.collection_check_boxes :user_ids, User.all, :id, :name
      -# この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 Knock-Knock Door編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.wrapper
  = render 'messages/side_bar'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規Knock-Knock Door
  = render partial: 'form', locals: { group: @group }

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title TravelLog
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/maps/index.html.haml
.html
  .head
    %meta{:charset => "utf-8"}/
  .body
    .wrapper
      -# = render "headerMap"
      -# = render "contentsMap"
      .headerMap
        .headerMap__logo
          Knock-Knock!
        .headerMap__link
          .headerMap__link__signUpBtn
            = link_to "サインアップ", "#", class: "signUpBtnx"
          .headerMap__link__loginBtn
            = link_to "ログイン", "#", class: "loginBtnx"
          .headerMap__link__myAboutBtn
            = link_to "マイアバウト", "#", class: "myAboutBtnx"

      .contentsMap
        .contentsMap__mapx
          .contentsMap__mapx__topWord
            情報交換コラボレーション！
          .contentsMap__mapx__middleMap
            マップ埋め込み
            ピン立てる-----

            -# TODO:
            #js-map.map


          .contentsMap__mapx__bottomAbout
            選択したピンのアバウト抜粋
            ピンまでの距離
            ピンの時間と国名都市名

      .footerMap
        .footerMap__foots
          .footerMap__foots__mycompany
            自己紹介
          .footerMap__foots__rights
            Copyright (C) 2020 Tahoo! Japan Corporation. All Rights Reserved.


    %script{:async => "", :defer => "defer", :src => "https://maps.googleapis.com/maps/api/js?key=【---】"}
    %script{:src => "map.js"}

app/views/messages/_main_chat.html.haml
.mainChat
  .mainChat__header
    .headTitle
      Knock-Knock Door
    .headProfile
      .headImage
        = link_to "アイコン）aboutmeの変数＠名前とリンク...", "#", class: "ownIntroduction"
      .headName
        = @group.name
        （個人名へ変換）
      .headPersonEdit
        = link_to "ノック相手選択", edit_group_path(@group), class: "headPerson"
    .headLink
      .headSnsName
        Facebook：
      .headSnsUrl
        = link_to "https://www.facebook.com/", class: "snsFacebook" do
          証明する外部リンク先

  .mainChat__contents
    .mainChat__contents__content
      〜〜〜 ノックノックトークスここから 〜〜〜
      .messages
        = render partial: "message", collection: @messages

  .mainChat__forms
    .mainChat__forms__former
      .form
        = form_for [@group, @message] do |fo|
          = fo.text_field :content, class: "inputText", placeholder: "  knock-knock message!"
          .form__pics
            = fo.label :image, class: "inputImageLabel" do
              = icon('fas', 'image', class: 'icon')
              = fo.file_field :image, class: "inputImage"
          = fo.submit "knock", class: "inputBtn"

app/views/messages/_message.html.haml
.message
  .upper-message
    .upper-message__user-name
      = message.user.name
    .upper-message__date
      世界時計TimeZone実装と国旗アイコン
      = message.created_at.strftime("%Y年%m月%d日 %H時%M分")

  .lower-message
    - if message.content.present?
      %p.lower-message__content
        = message.content
    = image_tag message.image.url, class: 'lower-message__image' if message.image.present?

app/views/messages/_side_bar.html.haml
.sideBar
  .sideBar__informs

    .sideBar__informs__infos
      %li= link_to "トップページ", root_path, class:"topBtn"
      %h3.currentUserName
        = current_user.name
      %li= link_to "ユーザ編集", edit_user_path(current_user), class:"userEditLink"
      %li= link_to "AboutMeプロフィール", aboutmes_path(current_user), class:"userAboutmeLink"
      %li= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"logoutLink"

    .sideBar__informs__groups
      %li= link_to "新しいドア探そ", new_group_path, class:"newKnockLink"
      - current_user.groups.each do |group|
        .group
          = link_to group_messages_path(group), class: "groupMessages" do
            .groupKnockName
              = group.name
              ノックドア個人名へ統一
            .groupKnockMessage
              = group.show_last_message

app/views/messages/index.html.haml
.html
  .head
  .body
    .wrapper
      = render "side_bar"
      = render "main_chat"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'

app/views/users/show.html.haml
.header
  .header__title
    = link_to "About Me", aboutmes_path, class: "header__title--text"
  .header__right
    = link_to current_user.name, user_path(current_user), class: "header__right--btn"
    = link_to "ノックノック画面に戻る", root_path, class: "header__right--btn"
    = link_to "新規プロフィール作成はこちら", new_aboutme_path, class: "header__right--btn"
.contents
  -# = yield
  .postTitle
    = @user.name

  - @abouts.each do |about|
    .content
      .content__left
        .content__left--image

      .content__right
        .content__right__top
          = link_to about.content, aboutmes_path(about.user), class: "content__right__top--title"
        .content__right__bottom
          .content__right__bottom--userName
            = image_tag about.image, class: "content__right__bottom--userName--btn"
            = link_to about.url, aboutmes_path(about.user), class: "content__right__bottom--userName--btn"
          .content__right__bottom--date
            = about.created_at